/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_rooho_lame_Mp3Lame */

#ifndef _Included_cc_rooho_lame_Mp3Lame
#define _Included_cc_rooho_lame_Mp3Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_rooho_lame_Mp3Lame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_cc_rooho_lame_Mp3Lame_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     cc_rooho_lame_Mp3Lame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_rooho_lame_Mp3Lame_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
